/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_announcement_free(a: number): void;
export function __wbg_attestation_free(a: number): void;
export function __wbg_eventdata_free(a: number): void;
export function __wbg_get_announcement_event_maturity_epoch(a: number): number;
export function __wbg_get_eventdata_event_maturity_epoch(a: number): number;
export function __wbg_set_announcement_event_maturity_epoch(a: number, b: number): void;
export function __wbg_set_eventdata_event_maturity_epoch(a: number, b: number): void;
export function announcement_announcement_signature(a: number, b: number): void;
export function announcement_event_id(a: number, b: number): void;
export function announcement_oracle_nonces(a: number, b: number): void;
export function announcement_oracle_public_key(a: number, b: number): void;
export function announcement_outcomes(a: number, b: number): void;
export function announcement_value(a: number): number;
export function attestation_oracle_public_key(a: number, b: number): void;
export function attestation_outcomes(a: number, b: number): void;
export function attestation_value(a: number): number;
export function eventdata_announcement_event_id(a: number, b: number): void;
export function eventdata_attestation(a: number, b: number): void;
export function eventdata_attestation_event_id(a: number, b: number): void;
export function eventdata_event_name(a: number, b: number): void;
export function eventdata_observed_outcome(a: number, b: number): void;
export function eventdata_value(a: number): number;
export function eventdata_announcement(a: number, b: number): void;
export function attestation_signatures(a: number, b: number): void;
export function eventdata_outcomes(a: number, b: number): void;
export function __wbg_kormir_free(a: number): void;
export function kormir_create_enum_event(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): number;
export function kormir_create_numeric_event(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): number;
export function kormir_decode_announcement(a: number, b: number): number;
export function kormir_decode_attestation(a: number, b: number): number;
export function kormir_get_public_key(a: number, b: number): void;
export function kormir_list_events(a: number): number;
export function kormir_new(a: number, b: number): number;
export function kormir_restore(a: number, b: number): number;
export function kormir_sign_enum_event(a: number, b: number, c: number, d: number, e: number): number;
export function kormir_sign_numeric_event(a: number, b: number, c: number, d: number): number;
export function main_js(): void;
export function rustsecp256k1zkp_v0_10_0_default_error_callback_fn(a: number, b: number): void;
export function rustsecp256k1zkp_v0_10_0_default_illegal_callback_fn(a: number, b: number): void;
export function rustsecp256k1_v0_10_0_context_create(a: number): number;
export function rustsecp256k1_v0_10_0_context_destroy(a: number): void;
export function rustsecp256k1_v0_10_0_default_error_callback_fn(a: number, b: number): void;
export function rustsecp256k1_v0_10_0_default_illegal_callback_fn(a: number, b: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hde63078dad085ba2(a: number, b: number, c: number, d: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hd49328b02eda7772(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h6e23e6acea90564f(a: number, b: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h02c7d9d8ab8173fa(a: number, b: number, c: number): void;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__hd304671d96792a2a(a: number, b: number, c: number, d: number): void;
export function __wbindgen_start(): void;
