services:
  mintd:
    image: joemphilips/bitcaster-mintd
    environment:
      CDK_MINTD_CTF_DEFAULT_KEYSET_CREATION: "one-vs-rest"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8085"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 30s

  cashu-me:
    image: joemphilips/cashu-me
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
